### ISSUE TITLE
echo ".DS_Store" >>~/.gitignore_global

### ISSUE THREAD

**Issue by teajaymars** [danielmcgraw/Jekyll-Base#3]
You don't need to add this boilerplate .gitignore file to every project :-) 
With nothing project-specific, this .gitignore file is superfluous -- Mac and Emacs stuff should be in gitignore_global. You could drop it and slim down your README.

(Great project by the way. Thank you.)

**Comment by danielmcgraw** [comment]
Thats a great point. I added that before I started playing with dotfiles and hated moving to a new machine and loosing my .gitignore. I'll pull that out. Thanks for the kind words too.
